{
    "itemGroup.moreBeautifulTorches": "More Beautiful Torches!",
    "block.more_beautiful_torches.acacia_log_redstone_torch": "Acacia Log Redstone Torch",
    "block.more_beautiful_torches.acacia_log_soul_torch": "Acacia Log Soul Torch", 
    "block.more_beautiful_torches.acacia_log_torch": "Acacia Log Torch", 
    "block.more_beautiful_torches.acacia_planks_redstone_torch": "Acacia Planks Redstone Torch", 
    "block.more_beautiful_torches.acacia_planks_soul_torch": "Acacia Planks Soul Torch", 
    "block.more_beautiful_torches.acacia_planks_torch": "Acacia Planks Torch", 
    "block.more_beautiful_torches.amethyst_block_redstone_torch": "Amethyst Block Redstone Torch", 
    "block.more_beautiful_torches.amethyst_block_soul_torch": "Amethyst Block Soul Torch", 
    "block.more_beautiful_torches.amethyst_block_torch": "Amethyst Block Torch", 
    "block.more_beautiful_torches.amethyst_cluster_redstone_torch": "Amethyst Cluster Redstone Torch", 
    "block.more_beautiful_torches.amethyst_cluster_soul_torch": "Amethyst Cluster Soul Torch", 
    "block.more_beautiful_torches.amethyst_cluster_torch": "Amethyst Cluster Torch", 
    "block.more_beautiful_torches.ancient_debris_redstone_torch": "Ancient Debris Redstone Torch", 
    "block.more_beautiful_torches.ancient_debris_soul_torch": "Ancient Debris Soul Torch", 
    "block.more_beautiful_torches.ancient_debris_torch": "Ancient Debris Torch", 
    "block.more_beautiful_torches.andesite_redstone_torch": "Andesite Redstone Torch", 
    "block.more_beautiful_torches.andesite_soul_torch": "Andesite Soul Torch", 
    "block.more_beautiful_torches.andesite_torch": "Andesite Torch",


    "block.more_beautiful_torches.bamboo_block_redstone_torch": "Bamboo Block Redstone Torch",
    "block.more_beautiful_torches.bamboo_block_soul_torch": "Bamboo Block Soul Torch",
    "block.more_beautiful_torches.bamboo_block_torch": "Bamboo Block Torch",
    "block.more_beautiful_torches.stripped_bamboo_block_redstone_torch": "Stripped Bamboo Block Redstone Torch",
    "block.more_beautiful_torches.stripped_bamboo_block_soul_torch": "Stripped Bamboo Block Soul Torch",
    "block.more_beautiful_torches.stripped_bamboo_block_torch": "Stripped Bamboo Block Torch",
    "block.more_beautiful_torches.bamboo_planks_redstone_torch": "Bamboo Planks Redstone Torch",
    "block.more_beautiful_torches.bamboo_planks_soul_torch": "Bamboo Planks Soul Torch",
    "block.more_beautiful_torches.bamboo_planks_torch": "Bamboo Planks Torch",

    "block.more_beautiful_torches.basalt_redstone_torch": "Basalt Redstone Torch", 
    "block.more_beautiful_torches.basalt_soul_torch": "Basalt Soul Torch", 
    "block.more_beautiful_torches.basalt_torch": "Basalt Torch", 
    "block.more_beautiful_torches.beehive_redstone_torch": "Beehive Redstone Torch", 
    "block.more_beautiful_torches.beehive_soul_torch": "Beehive Soul Torch", 
    "block.more_beautiful_torches.beehive_torch": "Beehive Torch", 
    "block.more_beautiful_torches.bee_nest_redstone_torch": "Bee Nest Redstone Torch", 
    "block.more_beautiful_torches.bee_nest_soul_torch": "Bee Nest Soul Torch", 
    "block.more_beautiful_torches.bee_nest_torch": "Bee Nest Torch", 
    "block.more_beautiful_torches.birch_log_redstone_torch": "Birch Log Redstone Torch", 
    "block.more_beautiful_torches.birch_log_soul_torch": "Birch Log Soul Torch", 
    "block.more_beautiful_torches.birch_log_torch": "Birch Log Torch", 
    "block.more_beautiful_torches.birch_planks_redstone_torch": "Birch Planks Redstone Torch", 
    "block.more_beautiful_torches.birch_planks_soul_torch": "Birch Planks Soul Torch", 
    "block.more_beautiful_torches.birch_planks_torch": "Birch Planks Torch", 
    "block.more_beautiful_torches.blackstone_redstone_torch": "Blackstone Redstone Torch", 
    "block.more_beautiful_torches.blackstone_soul_torch": "Blackstone Soul Torch", 
    "block.more_beautiful_torches.blackstone_torch": "Blackstone Torch", 
    "block.more_beautiful_torches.black_terracotta_redstone_torch": "Black Terracotta Redstone Torch", 
    "block.more_beautiful_torches.black_terracotta_soul_torch": "Black Terracotta Soul Torch", 
    "block.more_beautiful_torches.black_terracotta_torch": "Black Terracotta Torch", 
    "block.more_beautiful_torches.black_wool_redstone_torch": "Black Wool Redstone Torch", 
    "block.more_beautiful_torches.black_wool_soul_torch": "Black Wool Soul Torch", 
    "block.more_beautiful_torches.black_wool_torch": "Black Wool Torch", 
    "block.more_beautiful_torches.blue_ice_redstone_torch": "Blue Ice Redstone Torch", 
    "block.more_beautiful_torches.blue_ice_soul_torch": "Blue Ice Soul Torch", 
    "block.more_beautiful_torches.blue_ice_torch": "Blue Ice Torch", 
    "block.more_beautiful_torches.blue_terracotta_redstone_torch": "Blue Terracotta Redstone Torch", 
    "block.more_beautiful_torches.blue_terracotta_soul_torch": "Blue Terracotta Soul Torch", 
    "block.more_beautiful_torches.blue_terracotta_torch": "Blue Terracotta Torch", 
    "block.more_beautiful_torches.blue_wool_redstone_torch": "Blue Wool Redstone Torch", 
    "block.more_beautiful_torches.blue_wool_soul_torch": "Blue Wool Soul Torch", 
    "block.more_beautiful_torches.blue_wool_torch": "Blue Wool Torch", 
    "block.more_beautiful_torches.bone_block_redstone_torch": "Bone Block Redstone Torch", 
    "block.more_beautiful_torches.bone_block_soul_torch": "Bone Block Soul Torch", 
    "block.more_beautiful_torches.bone_block_torch": "Bone Block Torch", 
    "block.more_beautiful_torches.bookshelf_redstone_torch": "Bookshelf Redstone Torch", 
    "block.more_beautiful_torches.bookshelf_soul_torch": "Bookshelf Soul Torch", 
    "block.more_beautiful_torches.bookshelf_torch": "Bookshelf Torch", 
    "block.more_beautiful_torches.brain_coral_block_redstone_torch": "Brain Coral Block Redstone Torch", 
    "block.more_beautiful_torches.brain_coral_block_soul_torch": "Brain Coral Block Soul Torch", 
    "block.more_beautiful_torches.brain_coral_block_torch": "Brain Coral Block Torch", 
    "block.more_beautiful_torches.bricks_redstone_torch": "Bricks Redstone Torch", 
    "block.more_beautiful_torches.bricks_soul_torch": "Bricks Soul Torch", 
    "block.more_beautiful_torches.bricks_torch": "Bricks Torch", 
    "block.more_beautiful_torches.brown_mushroom_redstone_torch": "Brown Mushroom Redstone Torch", 
    "block.more_beautiful_torches.brown_mushroom_soul_torch": "Brown Mushroom Soul Torch", 
    "block.more_beautiful_torches.brown_mushroom_torch": "Brown Mushroom Torch", 
    "block.more_beautiful_torches.brown_mushroom_block_redstone_torch": "Brown Mushroom Block Redstone Torch", 
    "block.more_beautiful_torches.brown_mushroom_block_soul_torch": "Brown Mushroom Block Soul Torch", 
    "block.more_beautiful_torches.brown_mushroom_block_torch": "Brown Mushroom Block Torch", 
    "block.more_beautiful_torches.brown_terracotta_redstone_torch": "Brown Terracotta Redstone Torch", 
    "block.more_beautiful_torches.brown_terracotta_soul_torch": "Brown Terracotta Soul Torch", 
    "block.more_beautiful_torches.brown_terracotta_torch": "Brown Terracotta Torch", 
    "block.more_beautiful_torches.brown_wool_redstone_torch": "Brown Wool Redstone Torch", 
    "block.more_beautiful_torches.brown_wool_soul_torch": "Brown Wool Soul Torch", 
    "block.more_beautiful_torches.brown_wool_torch": "Brown Wool Torch", 
    "block.more_beautiful_torches.bubble_coral_block_redstone_torch": "Bubble Coral Block Redstone Torch", 
    "block.more_beautiful_torches.bubble_coral_block_soul_torch": "Bubble Coral Block Soul Torch", 
    "block.more_beautiful_torches.bubble_coral_block_torch": "Bubble Coral Block Torch", 
    "block.more_beautiful_torches.budding_amethyst_redstone_torch": "Budding Amethyst Redstone Torch", 
    "block.more_beautiful_torches.budding_amethyst_soul_torch": "Budding Amethyst Soul Torch", 
    "block.more_beautiful_torches.budding_amethyst_torch": "Budding Amethyst Torch", 
    "block.more_beautiful_torches.calcite_redstone_torch": "Calcite Redstone Torch", 
    "block.more_beautiful_torches.calcite_soul_torch": "Calcite Soul Torch", 
    "block.more_beautiful_torches.calcite_torch": "Calcite Torch", 
    "block.more_beautiful_torches.chiseled_deepslate_redstone_torch": "Chiseled Deepslate Redstone Torch", 
    "block.more_beautiful_torches.chiseled_deepslate_soul_torch": "Chiseled Deepslate Soul Torch", 
    "block.more_beautiful_torches.chiseled_deepslate_torch": "Chiseled Deepslate Torch", 
    "block.more_beautiful_torches.chiseled_nether_bricks_redstone_torch": "Chiseled Nether Bricks Redstone Torch", 
    "block.more_beautiful_torches.chiseled_nether_bricks_soul_torch": "Chiseled Nether Bricks Soul Torch", 
    "block.more_beautiful_torches.chiseled_nether_bricks_torch": "Chiseled Nether Bricks Torch", 
    "block.more_beautiful_torches.chiseled_polished_blackstone_redstone_torch": "Chiseled Polished Blackstone Redstone Torch", 
    "block.more_beautiful_torches.chiseled_polished_blackstone_soul_torch": "Chiseled Polished Blackstone Soul Torch", 
    "block.more_beautiful_torches.chiseled_polished_blackstone_torch": "Chiseled Polished Blackstone Torch", 
    "block.more_beautiful_torches.chiseled_quartz_block_redstone_torch": "Chiseled Quartz Block Redstone Torch", 
    "block.more_beautiful_torches.chiseled_quartz_block_soul_torch": "Chiseled Quartz Block Soul Torch", 
    "block.more_beautiful_torches.chiseled_quartz_block_torch": "Chiseled Quartz Block Torch", 
    "block.more_beautiful_torches.chiseled_red_sandstone_redstone_torch": "Chiseled Red Sandstone Redstone Torch", 
    "block.more_beautiful_torches.chiseled_red_sandstone_soul_torch": "Chiseled Red Sandstone Soul Torch", 
    "block.more_beautiful_torches.chiseled_red_sandstone_torch": "Chiseled Red Sandstone Torch", 
    "block.more_beautiful_torches.chiseled_sandstone_redstone_torch": "Chiseled Sandstone Redstone Torch", 
    "block.more_beautiful_torches.chiseled_sandstone_soul_torch": "Chiseled Sandstone Soul Torch", 
    "block.more_beautiful_torches.chiseled_sandstone_torch": "Chiseled Sandstone Torch", 
    "block.more_beautiful_torches.chiseled_stone_bricks_redstone_torch": "Chiseled Stone Bricks Redstone Torch", 
    "block.more_beautiful_torches.chiseled_stone_bricks_soul_torch": "Chiseled Stone Bricks Soul Torch", 
    "block.more_beautiful_torches.chiseled_stone_bricks_torch": "Chiseled Stone Bricks Torch", 
    "block.more_beautiful_torches.chorus_flower_redstone_torch": "Chorus Flower Redstone Torch", 
    "block.more_beautiful_torches.chorus_flower_soul_torch": "Chorus Flower Soul Torch", 
    "block.more_beautiful_torches.chorus_flower_torch": "Chorus Flower Torch", 
    "block.more_beautiful_torches.chorus_plant_redstone_torch": "Chorus Plant Redstone Torch", 
    "block.more_beautiful_torches.chorus_plant_soul_torch": "Chorus Plant Soul Torch", 
    "block.more_beautiful_torches.chorus_plant_torch": "Chorus Plant Torch", 
    "block.more_beautiful_torches.clay_redstone_torch": "Clay Redstone Torch", 
    "block.more_beautiful_torches.clay_soul_torch": "Clay Soul Torch", 
    "block.more_beautiful_torches.clay_torch": "Clay Torch", 
    "block.more_beautiful_torches.coal_block_redstone_torch": "Coal Block Redstone Torch", 
    "block.more_beautiful_torches.coal_block_soul_torch": "Coal Block Soul Torch", 
    "block.more_beautiful_torches.coal_block_torch": "Coal Block Torch", 
    "block.more_beautiful_torches.coal_ore_redstone_torch": "Coal Ore Redstone Torch", 
    "block.more_beautiful_torches.coal_ore_soul_torch": "Coal Ore Soul Torch", 
    "block.more_beautiful_torches.coal_ore_torch": "Coal Ore Torch", 
    "block.more_beautiful_torches.coarse_dirt_redstone_torch": "Coarse Dirt Redstone Torch", 
    "block.more_beautiful_torches.coarse_dirt_soul_torch": "Coarse Dirt Soul Torch", 
    "block.more_beautiful_torches.coarse_dirt_torch": "Coarse Dirt Torch", 
    "block.more_beautiful_torches.cobbled_deepslate_redstone_torch": "Cobbled Deepslate Redstone Torch", 
    "block.more_beautiful_torches.cobbled_deepslate_soul_torch": "Cobbled Deepslate Soul Torch", 
    "block.more_beautiful_torches.cobbled_deepslate_torch": "Cobbled Deepslate Torch", 
    "block.more_beautiful_torches.cobblestone_redstone_torch": "Cobblestone Redstone Torch", 
    "block.more_beautiful_torches.cobblestone_soul_torch": "Cobblestone Soul Torch", 
    "block.more_beautiful_torches.cobblestone_torch": "Cobblestone Torch", 
    "block.more_beautiful_torches.copper_block_redstone_torch": "Copper Block Redstone Torch", 
    "block.more_beautiful_torches.copper_block_soul_torch": "Copper Block Soul Torch", 
    "block.more_beautiful_torches.copper_block_torch": "Copper Block Torch", 
    "block.more_beautiful_torches.copper_ore_redstone_torch": "Copper Ore Redstone Torch", 
    "block.more_beautiful_torches.copper_ore_soul_torch": "Copper Ore Soul Torch", 
    "block.more_beautiful_torches.copper_ore_torch": "Copper Ore Torch", 
    "block.more_beautiful_torches.cracked_deepslate_bricks_redstone_torch": "Cracked Deepslate Bricks Redstone Torch", 
    "block.more_beautiful_torches.cracked_deepslate_bricks_soul_torch": "Cracked Deepslate Bricks Soul Torch", 
    "block.more_beautiful_torches.cracked_deepslate_bricks_torch": "Cracked Deepslate Bricks Torch", 
    "block.more_beautiful_torches.cracked_deepslate_tiles_redstone_torch": "Cracked Deepslate Tiles Redstone Torch", 
    "block.more_beautiful_torches.cracked_deepslate_tiles_soul_torch": "Cracked Deepslate Tiles Soul Torch", 
    "block.more_beautiful_torches.cracked_deepslate_tiles_torch": "Cracked Deepslate Tiles Torch", 
    "block.more_beautiful_torches.cracked_nether_bricks_redstone_torch": "Cracked Nether Bricks Redstone Torch", 
    "block.more_beautiful_torches.cracked_nether_bricks_soul_torch": "Cracked Nether Bricks Soul Torch", 
    "block.more_beautiful_torches.cracked_nether_bricks_torch": "Cracked Nether Bricks Torch", 
    "block.more_beautiful_torches.cracked_polished_blackstone_bricks_redstone_torch": "Cracked Polished Blackstone Bricks Redstone Torch", 
    "block.more_beautiful_torches.cracked_polished_blackstone_bricks_soul_torch": "Cracked Polished Blackstone Bricks Soul Torch", 
    "block.more_beautiful_torches.cracked_polished_blackstone_bricks_torch": "Cracked Polished Blackstone Bricks Torch", 
    "block.more_beautiful_torches.cracked_stone_bricks_redstone_torch": "Cracked Stone Bricks Redstone Torch", 
    "block.more_beautiful_torches.cracked_stone_bricks_soul_torch": "Cracked Stone Bricks Soul Torch", 
    "block.more_beautiful_torches.cracked_stone_bricks_torch": "Cracked Stone Bricks Torch", 
    "block.more_beautiful_torches.crimson_fungus_redstone_torch": "Crimson Fungus Redstone Torch", 
    "block.more_beautiful_torches.crimson_fungus_soul_torch": "Crimson Fungus Soul Torch", 
    "block.more_beautiful_torches.crimson_fungus_torch": "Crimson Fungus Torch", 
    "block.more_beautiful_torches.crimson_hyphae_redstone_torch": "Crimson Hyphae Redstone Torch", 
    "block.more_beautiful_torches.crimson_hyphae_soul_torch": "Crimson Hyphae Soul Torch", 
    "block.more_beautiful_torches.crimson_hyphae_torch": "Crimson Hyphae Torch", 
    "block.more_beautiful_torches.crimson_nylium_redstone_torch": "Crimson Nylium Redstone Torch", 
    "block.more_beautiful_torches.crimson_nylium_soul_torch": "Crimson Nylium Soul Torch", 
    "block.more_beautiful_torches.crimson_nylium_torch": "Crimson Nylium Torch", 
    "block.more_beautiful_torches.crimson_planks_redstone_torch": "Crimson Planks Redstone Torch", 
    "block.more_beautiful_torches.crimson_planks_soul_torch": "Crimson Planks Soul Torch", 
    "block.more_beautiful_torches.crimson_planks_torch": "Crimson Planks Torch", 
    "block.more_beautiful_torches.crimson_roots_redstone_torch": "Crimson Roots Redstone Torch", 
    "block.more_beautiful_torches.crimson_roots_soul_torch": "Crimson Roots Soul Torch", 
    "block.more_beautiful_torches.crimson_roots_torch": "Crimson Roots Torch", 
    "block.more_beautiful_torches.crying_obsidian_redstone_torch": "Crying Obsidian Redstone Torch", 
    "block.more_beautiful_torches.crying_obsidian_soul_torch": "Crying Obsidian Soul Torch", 
    "block.more_beautiful_torches.crying_obsidian_torch": "Crying Obsidian Torch", 
    "block.more_beautiful_torches.cut_copper_redstone_torch": "Cut Copper Redstone Torch", 
    "block.more_beautiful_torches.cut_copper_soul_torch": "Cut Copper Soul Torch", 
    "block.more_beautiful_torches.cut_copper_torch": "Cut Copper Torch", 
    "block.more_beautiful_torches.cut_red_sandstone_redstone_torch": "Cut Red Sandstone Redstone Torch", 
    "block.more_beautiful_torches.cut_red_sandstone_soul_torch": "Cut Red Sandstone Soul Torch", 
    "block.more_beautiful_torches.cut_red_sandstone_torch": "Cut Red Sandstone Torch", 
    "block.more_beautiful_torches.cut_sandstone_redstone_torch": "Cut Sandstone Redstone Torch", 
    "block.more_beautiful_torches.cut_sandstone_soul_torch": "Cut Sandstone Soul Torch", 
    "block.more_beautiful_torches.cut_sandstone_torch": "Cut Sandstone Torch", 
    "block.more_beautiful_torches.cyan_terracotta_redstone_torch": "Cyan Terracotta Redstone Torch", 
    "block.more_beautiful_torches.cyan_terracotta_soul_torch": "Cyan Terracotta Soul Torch", 
    "block.more_beautiful_torches.cyan_terracotta_torch": "Cyan Terracotta Torch", 
    "block.more_beautiful_torches.cyan_wool_redstone_torch": "Cyan Wool Redstone Torch", 
    "block.more_beautiful_torches.cyan_wool_soul_torch": "Cyan Wool Soul Torch", 
    "block.more_beautiful_torches.cyan_wool_torch": "Cyan Wool Torch", 
    "block.more_beautiful_torches.dark_oak_log_redstone_torch": "Dark Oak Log Redstone Torch", 
    "block.more_beautiful_torches.dark_oak_log_soul_torch": "Dark Oak Log Soul Torch", 
    "block.more_beautiful_torches.dark_oak_log_torch": "Dark Oak Log Torch", 
    "block.more_beautiful_torches.dark_oak_planks_redstone_torch": "Dark Oak Planks Redstone Torch", 
    "block.more_beautiful_torches.dark_oak_planks_soul_torch": "Dark Oak Planks Soul Torch", 
    "block.more_beautiful_torches.dark_oak_planks_torch": "Dark Oak Planks Torch", 
    "block.more_beautiful_torches.dark_prismarine_redstone_torch": "Dark Prismarine Redstone Torch", 
    "block.more_beautiful_torches.dark_prismarine_soul_torch": "Dark Prismarine Soul Torch", 
    "block.more_beautiful_torches.dark_prismarine_torch": "Dark Prismarine Torch", 
    "block.more_beautiful_torches.dead_brain_coral_block_redstone_torch": "Dead Brain Coral Block Redstone Torch", 
    "block.more_beautiful_torches.dead_brain_coral_block_soul_torch": "Dead Brain Coral Block Soul Torch", 
    "block.more_beautiful_torches.dead_brain_coral_block_torch": "Dead Brain Coral Block Torch", 
    "block.more_beautiful_torches.dead_bubble_coral_block_redstone_torch": "Dead Bubble Coral Block Redstone Torch", 
    "block.more_beautiful_torches.dead_bubble_coral_block_soul_torch": "Dead Bubble Coral Block Soul Torch", 
    "block.more_beautiful_torches.dead_bubble_coral_block_torch": "Dead Bubble Coral Block Torch", 
    "block.more_beautiful_torches.dead_fire_coral_block_redstone_torch": "Dead Fire Coral Block Redstone Torch", 
    "block.more_beautiful_torches.dead_fire_coral_block_soul_torch": "Dead Fire Coral Block Soul Torch", 
    "block.more_beautiful_torches.dead_fire_coral_block_torch": "Dead Fire Coral Block Torch", 
    "block.more_beautiful_torches.dead_horn_coral_block_redstone_torch": "Dead Horn Coral Block Redstone Torch", 
    "block.more_beautiful_torches.dead_horn_coral_block_soul_torch": "Dead Horn Coral Block Soul Torch", 
    "block.more_beautiful_torches.dead_horn_coral_block_torch": "Dead Horn Coral Block Torch", 
    "block.more_beautiful_torches.dead_tube_coral_block_redstone_torch": "Dead Tube Coral Block Redstone Torch", 
    "block.more_beautiful_torches.dead_tube_coral_block_soul_torch": "Dead Tube Coral Block Soul Torch", 
    "block.more_beautiful_torches.dead_tube_coral_block_torch": "Dead Tube Coral Block Torch", 
    "block.more_beautiful_torches.deepslate_redstone_torch": "Deepslate Redstone Torch", 
    "block.more_beautiful_torches.deepslate_soul_torch": "Deepslate Soul Torch", 
    "block.more_beautiful_torches.deepslate_torch": "Deepslate Torch", 
    "block.more_beautiful_torches.deepslate_bricks_redstone_torch": "Deepslate Bricks Redstone Torch", 
    "block.more_beautiful_torches.deepslate_bricks_soul_torch": "Deepslate Bricks Soul Torch", 
    "block.more_beautiful_torches.deepslate_bricks_torch": "Deepslate Bricks Torch", 
    "block.more_beautiful_torches.deepslate_coal_ore_redstone_torch": "Deepslate Coal Ore Redstone Torch", 
    "block.more_beautiful_torches.deepslate_coal_ore_soul_torch": "Deepslate Coal Ore Soul Torch", 
    "block.more_beautiful_torches.deepslate_coal_ore_torch": "Deepslate Coal Ore Torch", 
    "block.more_beautiful_torches.deepslate_copper_ore_redstone_torch": "Deepslate Copper Ore Redstone Torch", 
    "block.more_beautiful_torches.deepslate_copper_ore_soul_torch": "Deepslate Copper Ore Soul Torch", 
    "block.more_beautiful_torches.deepslate_copper_ore_torch": "Deepslate Copper Ore Torch", 
    "block.more_beautiful_torches.deepslate_diamond_ore_redstone_torch": "Deepslate Diamond Ore Redstone Torch", 
    "block.more_beautiful_torches.deepslate_diamond_ore_soul_torch": "Deepslate Diamond Ore Soul Torch", 
    "block.more_beautiful_torches.deepslate_diamond_ore_torch": "Deepslate Diamond Ore Torch", 
    "block.more_beautiful_torches.deepslate_emerald_ore_redstone_torch": "Deepslate Emerald Ore Redstone Torch", 
    "block.more_beautiful_torches.deepslate_emerald_ore_soul_torch": "Deepslate Emerald Ore Soul Torch", 
    "block.more_beautiful_torches.deepslate_emerald_ore_torch": "Deepslate Emerald Ore Torch", 
    "block.more_beautiful_torches.deepslate_gold_ore_redstone_torch": "Deepslate Gold Ore Redstone Torch", 
    "block.more_beautiful_torches.deepslate_gold_ore_soul_torch": "Deepslate Gold Ore Soul Torch", 
    "block.more_beautiful_torches.deepslate_gold_ore_torch": "Deepslate Gold Ore Torch", 
    "block.more_beautiful_torches.deepslate_iron_ore_redstone_torch": "Deepslate Iron Ore Redstone Torch", 
    "block.more_beautiful_torches.deepslate_iron_ore_soul_torch": "Deepslate Iron Ore Soul Torch", 
    "block.more_beautiful_torches.deepslate_iron_ore_torch": "Deepslate Iron Ore Torch", 
    "block.more_beautiful_torches.deepslate_lapis_ore_redstone_torch": "Deepslate Lapis Ore Redstone Torch", 
    "block.more_beautiful_torches.deepslate_lapis_ore_soul_torch": "Deepslate Lapis Ore Soul Torch", 
    "block.more_beautiful_torches.deepslate_lapis_ore_torch": "Deepslate Lapis Ore Torch", 
    "block.more_beautiful_torches.deepslate_redstone_ore_redstone_torch": "Deepslate Redstone Ore Redstone Torch", 
    "block.more_beautiful_torches.deepslate_redstone_ore_soul_torch": "Deepslate Redstone Ore Soul Torch", 
    "block.more_beautiful_torches.deepslate_redstone_ore_torch": "Deepslate Redstone Ore Torch", 
    "block.more_beautiful_torches.deepslate_tiles_redstone_torch": "Deepslate Tiles Redstone Torch", 
    "block.more_beautiful_torches.deepslate_tiles_soul_torch": "Deepslate Tiles Soul Torch", 
    "block.more_beautiful_torches.deepslate_tiles_torch": "Deepslate Tiles Torch", 
    "block.more_beautiful_torches.diamond_block_redstone_torch": "Diamond Block Redstone Torch", 
    "block.more_beautiful_torches.diamond_block_soul_torch": "Diamond Block Soul Torch", 
    "block.more_beautiful_torches.diamond_block_torch": "Diamond Block Torch", 
    "block.more_beautiful_torches.diamond_ore_redstone_torch": "Diamond Ore Redstone Torch", 
    "block.more_beautiful_torches.diamond_ore_soul_torch": "Diamond Ore Soul Torch", 
    "block.more_beautiful_torches.diamond_ore_torch": "Diamond Ore Torch", 
    "block.more_beautiful_torches.diorite_redstone_torch": "Diorite Redstone Torch", 
    "block.more_beautiful_torches.diorite_soul_torch": "Diorite Soul Torch", 
    "block.more_beautiful_torches.diorite_torch": "Diorite Torch", 
    "block.more_beautiful_torches.dirt_redstone_torch": "Dirt Redstone Torch", 
    "block.more_beautiful_torches.dirt_soul_torch": "Dirt Soul Torch", 
    "block.more_beautiful_torches.dirt_torch": "Dirt Torch", 
    "block.more_beautiful_torches.dried_kelp_block_redstone_torch": "Dried Kelp Block Redstone Torch", 
    "block.more_beautiful_torches.dried_kelp_block_soul_torch": "Dried Kelp Block Soul Torch", 
    "block.more_beautiful_torches.dried_kelp_block_torch": "Dried Kelp Block Torch", 
    "block.more_beautiful_torches.dripstone_block_redstone_torch": "Dripstone Block Redstone Torch", 
    "block.more_beautiful_torches.dripstone_block_soul_torch": "Dripstone Block Soul Torch", 
    "block.more_beautiful_torches.dripstone_block_torch": "Dripstone Block Torch", 
    "block.more_beautiful_torches.emerald_block_redstone_torch": "Emerald Block Redstone Torch", 
    "block.more_beautiful_torches.emerald_block_soul_torch": "Emerald Block Soul Torch", 
    "block.more_beautiful_torches.emerald_block_torch": "Emerald Block Torch", 
    "block.more_beautiful_torches.emerald_ore_redstone_torch": "Emerald Ore Redstone Torch", 
    "block.more_beautiful_torches.emerald_ore_soul_torch": "Emerald Ore Soul Torch", 
    "block.more_beautiful_torches.emerald_ore_torch": "Emerald Ore Torch", 
    "block.more_beautiful_torches.end_portal_frame_redstone_torch": "End Portal Frame Redstone Torch", 
    "block.more_beautiful_torches.end_portal_frame_soul_torch": "End Portal Frame Soul Torch", 
    "block.more_beautiful_torches.end_portal_frame_torch": "End Portal Frame Torch", 
    "block.more_beautiful_torches.end_stone_redstone_torch": "End Stone Redstone Torch", 
    "block.more_beautiful_torches.end_stone_soul_torch": "End Stone Soul Torch", 
    "block.more_beautiful_torches.end_stone_torch": "End Stone Torch", 
    "block.more_beautiful_torches.end_stone_bricks_redstone_torch": "End Stone Bricks Redstone Torch", 
    "block.more_beautiful_torches.end_stone_bricks_soul_torch": "End Stone Bricks Soul Torch", 
    "block.more_beautiful_torches.end_stone_bricks_torch": "End Stone Bricks Torch", 
    "block.more_beautiful_torches.exposed_copper_redstone_torch": "Exposed Copper Redstone Torch", 
    "block.more_beautiful_torches.exposed_copper_soul_torch": "Exposed Copper Soul Torch", 
    "block.more_beautiful_torches.exposed_copper_torch": "Exposed Copper Torch", 
    "block.more_beautiful_torches.exposed_cut_copper_redstone_torch": "Exposed Cut Copper Redstone Torch", 
    "block.more_beautiful_torches.exposed_cut_copper_soul_torch": "Exposed Cut Copper Soul Torch", 
    "block.more_beautiful_torches.exposed_cut_copper_torch": "Exposed Cut Copper Torch", 
    "block.more_beautiful_torches.fire_coral_block_redstone_torch": "Fire Coral Block Redstone Torch", 
    "block.more_beautiful_torches.fire_coral_block_soul_torch": "Fire Coral Block Soul Torch", 
    "block.more_beautiful_torches.fire_coral_block_torch": "Fire Coral Block Torch",
    "block.more_beautiful_torches.gilded_blackstone_redstone_torch": "Gilded Blackstone Redstone Torch", 
    "block.more_beautiful_torches.gilded_blackstone_soul_torch": "Gilded Blackstone Soul Torch", 
    "block.more_beautiful_torches.gilded_blackstone_torch": "Gilded Blackstone Torch", 
    "block.more_beautiful_torches.glowstone_redstone_torch": "Glowstone Redstone Torch", 
    "block.more_beautiful_torches.glowstone_soul_torch": "Glowstone Soul Torch", 
    "block.more_beautiful_torches.glowstone_torch": "Glowstone Torch", 
    "block.more_beautiful_torches.gold_block_redstone_torch": "Gold Block Redstone Torch", 
    "block.more_beautiful_torches.gold_block_soul_torch": "Gold Block Soul Torch", 
    "block.more_beautiful_torches.gold_block_torch": "Gold Block Torch", 
    "block.more_beautiful_torches.gold_ore_redstone_torch": "Gold Ore Redstone Torch", 
    "block.more_beautiful_torches.gold_ore_soul_torch": "Gold Ore Soul Torch", 
    "block.more_beautiful_torches.gold_ore_torch": "Gold Ore Torch", 
    "block.more_beautiful_torches.granite_redstone_torch": "Granite Redstone Torch", 
    "block.more_beautiful_torches.granite_soul_torch": "Granite Soul Torch", 
    "block.more_beautiful_torches.granite_torch": "Granite Torch", 
    "block.more_beautiful_torches.gravel_redstone_torch": "Gravel Redstone Torch", 
    "block.more_beautiful_torches.gravel_soul_torch": "Gravel Soul Torch", 
    "block.more_beautiful_torches.gravel_torch": "Gravel Torch", 
    "block.more_beautiful_torches.gray_terracotta_redstone_torch": "Gray Terracotta Redstone Torch", 
    "block.more_beautiful_torches.gray_terracotta_soul_torch": "Gray Terracotta Soul Torch", 
    "block.more_beautiful_torches.gray_terracotta_torch": "Gray Terracotta Torch", 
    "block.more_beautiful_torches.gray_wool_redstone_torch": "Gray Wool Redstone Torch", 
    "block.more_beautiful_torches.gray_wool_soul_torch": "Gray Wool Soul Torch", 
    "block.more_beautiful_torches.gray_wool_torch": "Gray Wool Torch", 
    "block.more_beautiful_torches.green_terracotta_redstone_torch": "Green Terracotta Redstone Torch", 
    "block.more_beautiful_torches.green_terracotta_soul_torch": "Green Terracotta Soul Torch", 
    "block.more_beautiful_torches.green_terracotta_torch": "Green Terracotta Torch", 
    "block.more_beautiful_torches.green_wool_redstone_torch": "Green Wool Redstone Torch", 
    "block.more_beautiful_torches.green_wool_soul_torch": "Green Wool Soul Torch", 
    "block.more_beautiful_torches.green_wool_torch": "Green Wool Torch", 
    "block.more_beautiful_torches.hay_block_redstone_torch": "Hay Block Redstone Torch", 
    "block.more_beautiful_torches.hay_block_soul_torch": "Hay Block Soul Torch", 
    "block.more_beautiful_torches.hay_block_torch": "Hay Block Torch", 
    "block.more_beautiful_torches.honeycomb_block_redstone_torch": "Honeycomb Block Redstone Torch", 
    "block.more_beautiful_torches.honeycomb_block_soul_torch": "Honeycomb Block Soul Torch", 
    "block.more_beautiful_torches.honeycomb_block_torch": "Honeycomb Block Torch", 
    "block.more_beautiful_torches.honey_block_redstone_torch": "Honey Block Redstone Torch", 
    "block.more_beautiful_torches.honey_block_soul_torch": "Honey Block Soul Torch", 
    "block.more_beautiful_torches.honey_block_torch": "Honey Block Torch", 
    "block.more_beautiful_torches.horn_coral_block_redstone_torch": "Horn Coral Block Redstone Torch", 
    "block.more_beautiful_torches.horn_coral_block_soul_torch": "Horn Coral Block Soul Torch", 
    "block.more_beautiful_torches.horn_coral_block_torch": "Horn Coral Block Torch", 
    "block.more_beautiful_torches.ice_redstone_torch": "Ice Redstone Torch", 
    "block.more_beautiful_torches.ice_soul_torch": "Ice Soul Torch", 
    "block.more_beautiful_torches.ice_torch": "Ice Torch", 
    "block.more_beautiful_torches.iron_bars_redstone_torch": "Iron Bars Redstone Torch", 
    "block.more_beautiful_torches.iron_bars_soul_torch": "Iron Bars Soul Torch", 
    "block.more_beautiful_torches.iron_bars_torch": "Iron Bars Torch", 
    "block.more_beautiful_torches.iron_block_redstone_torch": "Iron Block Redstone Torch", 
    "block.more_beautiful_torches.iron_block_soul_torch": "Iron Block Soul Torch", 
    "block.more_beautiful_torches.iron_block_torch": "Iron Block Torch", 
    "block.more_beautiful_torches.iron_ore_redstone_torch": "Iron Ore Redstone Torch", 
    "block.more_beautiful_torches.iron_ore_soul_torch": "Iron Ore Soul Torch", 
    "block.more_beautiful_torches.iron_ore_torch": "Iron Ore Torch", 
    "block.more_beautiful_torches.jungle_log_redstone_torch": "Jungle Log Redstone Torch", 
    "block.more_beautiful_torches.jungle_log_soul_torch": "Jungle Log Soul Torch", 
    "block.more_beautiful_torches.jungle_log_torch": "Jungle Log Torch", 
    "block.more_beautiful_torches.jungle_planks_redstone_torch": "Jungle Planks Redstone Torch", 
    "block.more_beautiful_torches.jungle_planks_soul_torch": "Jungle Planks Soul Torch", 
    "block.more_beautiful_torches.jungle_planks_torch": "Jungle Planks Torch", 
    "block.more_beautiful_torches.lapis_block_redstone_torch": "Lapis Block Redstone Torch", 
    "block.more_beautiful_torches.lapis_block_soul_torch": "Lapis Block Soul Torch", 
    "block.more_beautiful_torches.lapis_block_torch": "Lapis Block Torch", 
    "block.more_beautiful_torches.lapis_ore_redstone_torch": "Lapis Ore Redstone Torch", 
    "block.more_beautiful_torches.lapis_ore_soul_torch": "Lapis Ore Soul Torch", 
    "block.more_beautiful_torches.lapis_ore_torch": "Lapis Ore Torch", 
    "block.more_beautiful_torches.light_blue_terracotta_redstone_torch": "Light Blue Terracotta Redstone Torch", 
    "block.more_beautiful_torches.light_blue_terracotta_soul_torch": "Light Blue Terracotta Soul Torch", 
    "block.more_beautiful_torches.light_blue_terracotta_torch": "Light Blue Terracotta Torch", 
    "block.more_beautiful_torches.light_blue_wool_redstone_torch": "Light Blue Wool Redstone Torch", 
    "block.more_beautiful_torches.light_blue_wool_soul_torch": "Light Blue Wool Soul Torch", 
    "block.more_beautiful_torches.light_blue_wool_torch": "Light Blue Wool Torch", 
    "block.more_beautiful_torches.light_gray_terracotta_redstone_torch": "Light Gray Terracotta Redstone Torch", 
    "block.more_beautiful_torches.light_gray_terracotta_soul_torch": "Light Gray Terracotta Soul Torch", 
    "block.more_beautiful_torches.light_gray_terracotta_torch": "Light Gray Terracotta Torch", 
    "block.more_beautiful_torches.light_gray_wool_redstone_torch": "Light Gray Wool Redstone Torch", 
    "block.more_beautiful_torches.light_gray_wool_soul_torch": "Light Gray Wool Soul Torch", 
    "block.more_beautiful_torches.light_gray_wool_torch": "Light Gray Wool Torch", 
    "block.more_beautiful_torches.lime_terracotta_redstone_torch": "Lime Terracotta Redstone Torch", 
    "block.more_beautiful_torches.lime_terracotta_soul_torch": "Lime Terracotta Soul Torch", 
    "block.more_beautiful_torches.lime_terracotta_torch": "Lime Terracotta Torch", 
    "block.more_beautiful_torches.lime_wool_redstone_torch": "Lime Wool Redstone Torch", 
    "block.more_beautiful_torches.lime_wool_soul_torch": "Lime Wool Soul Torch", 
    "block.more_beautiful_torches.lime_wool_torch": "Lime Wool Torch", 
    "block.more_beautiful_torches.lodestone_redstone_torch": "Lodestone Redstone Torch", 
    "block.more_beautiful_torches.lodestone_soul_torch": "Lodestone Soul Torch", 
    "block.more_beautiful_torches.lodestone_torch": "Lodestone Torch", 
    "block.more_beautiful_torches.magenta_terracotta_redstone_torch": "Magenta Terracotta Redstone Torch", 
    "block.more_beautiful_torches.magenta_terracotta_soul_torch": "Magenta Terracotta Soul Torch", 
    "block.more_beautiful_torches.magenta_terracotta_torch": "Magenta Terracotta Torch", 
    "block.more_beautiful_torches.magenta_wool_redstone_torch": "Magenta Wool Redstone Torch", 
    "block.more_beautiful_torches.magenta_wool_soul_torch": "Magenta Wool Soul Torch", 
    "block.more_beautiful_torches.magenta_wool_torch": "Magenta Wool Torch", 
    "block.more_beautiful_torches.magma_block_redstone_torch": "Magma Block Redstone Torch", 
    "block.more_beautiful_torches.magma_block_soul_torch": "Magma Block Soul Torch", 
    "block.more_beautiful_torches.magma_block_torch": "Magma Block Torch", 
    "block.more_beautiful_torches.mangrove_log_redstone_torch": "Mangrove Log Redstone Torch", 
    "block.more_beautiful_torches.mangrove_log_soul_torch": "Mangrove Log Soul Torch", 
    "block.more_beautiful_torches.mangrove_log_torch": "Mangrove Log Torch", 
    "block.more_beautiful_torches.mangrove_planks_redstone_torch": "Mangrove Planks Redstone Torch", 
    "block.more_beautiful_torches.mangrove_planks_soul_torch": "Mangrove Planks Soul Torch", 
    "block.more_beautiful_torches.mangrove_planks_torch": "Mangrove Planks Torch", 
    "block.more_beautiful_torches.melon_redstone_torch": "Melon Redstone Torch", 
    "block.more_beautiful_torches.melon_soul_torch": "Melon Soul Torch", 
    "block.more_beautiful_torches.melon_torch": "Melon Torch", 
    "block.more_beautiful_torches.mossy_cobblestone_redstone_torch": "Mossy Cobblestone Redstone Torch", 
    "block.more_beautiful_torches.mossy_cobblestone_soul_torch": "Mossy Cobblestone Soul Torch", 
    "block.more_beautiful_torches.mossy_cobblestone_torch": "Mossy Cobblestone Torch", 
    "block.more_beautiful_torches.mossy_stone_bricks_redstone_torch": "Mossy Stone Bricks Redstone Torch", 
    "block.more_beautiful_torches.mossy_stone_bricks_soul_torch": "Mossy Stone Bricks Soul Torch", 
    "block.more_beautiful_torches.mossy_stone_bricks_torch": "Mossy Stone Bricks Torch", 
    "block.more_beautiful_torches.moss_block_redstone_torch": "Moss Block Redstone Torch", 
    "block.more_beautiful_torches.moss_block_soul_torch": "Moss Block Soul Torch", 
    "block.more_beautiful_torches.moss_block_torch": "Moss Block Torch", 
    "block.more_beautiful_torches.mud_redstone_torch": "Mud Redstone Torch", 
    "block.more_beautiful_torches.mud_soul_torch": "Mud Soul Torch", 
    "block.more_beautiful_torches.mud_torch": "Mud Torch", 
    "block.more_beautiful_torches.muddy_mangrove_roots_redstone_torch": "Muddy Mangrove Roots Redstone Torch", 
    "block.more_beautiful_torches.muddy_mangrove_roots_soul_torch": "Muddy Mangrove Roots Soul Torch", 
    "block.more_beautiful_torches.muddy_mangrove_roots_torch": "Muddy Mangrove Roots Torch", 
    "block.more_beautiful_torches.mud_bricks_redstone_torch": "Mud Bricks Redstone Torch", 
    "block.more_beautiful_torches.mud_bricks_soul_torch": "Mud Bricks Soul Torch", 
    "block.more_beautiful_torches.mud_bricks_torch": "Mud Bricks Torch", 
    "block.more_beautiful_torches.mushroom_stem_redstone_torch": "Mushroom Stem Redstone Torch", 
    "block.more_beautiful_torches.mushroom_stem_soul_torch": "Mushroom Stem Soul Torch", 
    "block.more_beautiful_torches.mushroom_stem_torch": "Mushroom Stem Torch", 
    "block.more_beautiful_torches.mycelium_redstone_torch": "Mycelium Redstone Torch", 
    "block.more_beautiful_torches.mycelium_soul_torch": "Mycelium Soul Torch", 
    "block.more_beautiful_torches.mycelium_torch": "Mycelium Torch", 
    "block.more_beautiful_torches.netherite_block_redstone_torch": "Netherite Block Redstone Torch", 
    "block.more_beautiful_torches.netherite_block_soul_torch": "Netherite Block Soul Torch", 
    "block.more_beautiful_torches.netherite_block_torch": "Netherite Block Torch", 
    "block.more_beautiful_torches.netherrack_redstone_torch": "Netherrack Redstone Torch", 
    "block.more_beautiful_torches.netherrack_soul_torch": "Netherrack Soul Torch", 
    "block.more_beautiful_torches.netherrack_torch": "Netherrack Torch", 
    "block.more_beautiful_torches.nether_bricks_redstone_torch": "Nether Bricks Redstone Torch", 
    "block.more_beautiful_torches.nether_bricks_soul_torch": "Nether Bricks Soul Torch", 
    "block.more_beautiful_torches.nether_bricks_torch": "Nether Bricks Torch", 
    "block.more_beautiful_torches.nether_gold_ore_redstone_torch": "Nether Gold Ore Redstone Torch", 
    "block.more_beautiful_torches.nether_gold_ore_soul_torch": "Nether Gold Ore Soul Torch", 
    "block.more_beautiful_torches.nether_gold_ore_torch": "Nether Gold Ore Torch", 
    "block.more_beautiful_torches.nether_quartz_ore_redstone_torch": "Nether Quartz Ore Redstone Torch", 
    "block.more_beautiful_torches.nether_quartz_ore_soul_torch": "Nether Quartz Ore Soul Torch", 
    "block.more_beautiful_torches.nether_quartz_ore_torch": "Nether Quartz Ore Torch", 
    "block.more_beautiful_torches.nether_wart_block_redstone_torch": "Nether Wart Block Redstone Torch", 
    "block.more_beautiful_torches.nether_wart_block_soul_torch": "Nether Wart Block Soul Torch", 
    "block.more_beautiful_torches.nether_wart_block_torch": "Nether Wart Block Torch", 
    "block.more_beautiful_torches.oak_log_redstone_torch": "Oak Log Redstone Torch", 
    "block.more_beautiful_torches.oak_log_soul_torch": "Oak Log Soul Torch", 
    "block.more_beautiful_torches.oak_log_torch": "Oak Log Torch", 
    "block.more_beautiful_torches.oak_planks_redstone_torch": "Oak Planks Redstone Torch", 
    "block.more_beautiful_torches.oak_planks_soul_torch": "Oak Planks Soul Torch", 
    "block.more_beautiful_torches.oak_planks_torch": "Oak Planks Torch", 
    "block.more_beautiful_torches.obsidian_redstone_torch": "Obsidian Redstone Torch", 
    "block.more_beautiful_torches.obsidian_soul_torch": "Obsidian Soul Torch", 
    "block.more_beautiful_torches.obsidian_torch": "Obsidian Torch", 
    "block.more_beautiful_torches.ochre_froglight_redstone_torch": "Ochre Froglight Redstone Torch", 
    "block.more_beautiful_torches.ochre_froglight_soul_torch": "Ochre Froglight Soul Torch", 
    "block.more_beautiful_torches.ochre_froglight_torch": "Ochre Froglight Torch", 
    "block.more_beautiful_torches.orange_terracotta_redstone_torch": "Orange Terracotta Redstone Torch", 
    "block.more_beautiful_torches.orange_terracotta_soul_torch": "Orange Terracotta Soul Torch", 
    "block.more_beautiful_torches.orange_terracotta_torch": "Orange Terracotta Torch", 
    "block.more_beautiful_torches.orange_wool_redstone_torch": "Orange Wool Redstone Torch", 
    "block.more_beautiful_torches.orange_wool_soul_torch": "Orange Wool Soul Torch", 
    "block.more_beautiful_torches.orange_wool_torch": "Orange Wool Torch", 
    "block.more_beautiful_torches.oxidized_copper_redstone_torch": "Oxidized Copper Redstone Torch", 
    "block.more_beautiful_torches.oxidized_copper_soul_torch": "Oxidized Copper Soul Torch", 
    "block.more_beautiful_torches.oxidized_copper_torch": "Oxidized Copper Torch", 
    "block.more_beautiful_torches.oxidized_cut_copper_redstone_torch": "Oxidized Cut Copper Redstone Torch", 
    "block.more_beautiful_torches.oxidized_cut_copper_soul_torch": "Oxidized Cut Copper Soul Torch", 
    "block.more_beautiful_torches.oxidized_cut_copper_torch": "Oxidized Cut Copper Torch", 
    "block.more_beautiful_torches.packed_ice_redstone_torch": "Packed Ice Redstone Torch", 
    "block.more_beautiful_torches.packed_ice_soul_torch": "Packed Ice Soul Torch", 
    "block.more_beautiful_torches.packed_ice_torch": "Packed Ice Torch", 
    "block.more_beautiful_torches.packed_mud_redstone_torch": "Packed Mud Redstone Torch", 
    "block.more_beautiful_torches.packed_mud_soul_torch": "Packed Mud Soul Torch", 
    "block.more_beautiful_torches.packed_mud_torch": "Packed Mud Torch", 
    "block.more_beautiful_torches.pearlescent_froglight_redstone_torch": "Pearlescent Froglight Redstone Torch", 
    "block.more_beautiful_torches.pearlescent_froglight_soul_torch": "Pearlescent Froglight Soul Torch", 
    "block.more_beautiful_torches.pearlescent_froglight_torch": "Pearlescent Froglight Torch", 
    "block.more_beautiful_torches.pink_terracotta_redstone_torch": "Pink Terracotta Redstone Torch", 
    "block.more_beautiful_torches.pink_terracotta_soul_torch": "Pink Terracotta Soul Torch", 
    "block.more_beautiful_torches.pink_terracotta_torch": "Pink Terracotta Torch", 
    "block.more_beautiful_torches.pink_wool_redstone_torch": "Pink Wool Redstone Torch", 
    "block.more_beautiful_torches.pink_wool_soul_torch": "Pink Wool Soul Torch", 
    "block.more_beautiful_torches.pink_wool_torch": "Pink Wool Torch", 
    "block.more_beautiful_torches.polished_andesite_redstone_torch": "Polished Andesite Redstone Torch", 
    "block.more_beautiful_torches.polished_andesite_soul_torch": "Polished Andesite Soul Torch", 
    "block.more_beautiful_torches.polished_andesite_torch": "Polished Andesite Torch", 
    "block.more_beautiful_torches.polished_basalt_redstone_torch": "Polished Basalt Redstone Torch", 
    "block.more_beautiful_torches.polished_basalt_soul_torch": "Polished Basalt Soul Torch", 
    "block.more_beautiful_torches.polished_basalt_torch": "Polished Basalt Torch", 
    "block.more_beautiful_torches.polished_blackstone_redstone_torch": "Polished Blackstone Redstone Torch", 
    "block.more_beautiful_torches.polished_blackstone_soul_torch": "Polished Blackstone Soul Torch", 
    "block.more_beautiful_torches.polished_blackstone_torch": "Polished Blackstone Torch", 
    "block.more_beautiful_torches.polished_blackstone_bricks_redstone_torch": "Polished Blackstone Bricks Redstone Torch", 
    "block.more_beautiful_torches.polished_blackstone_bricks_soul_torch": "Polished Blackstone Bricks Soul Torch", 
    "block.more_beautiful_torches.polished_blackstone_bricks_torch": "Polished Blackstone Bricks Torch", 
    "block.more_beautiful_torches.polished_deepslate_redstone_torch": "Polished Deepslate Redstone Torch", 
    "block.more_beautiful_torches.polished_deepslate_soul_torch": "Polished Deepslate Soul Torch", 
    "block.more_beautiful_torches.polished_deepslate_torch": "Polished Deepslate Torch", 
    "block.more_beautiful_torches.polished_diorite_redstone_torch": "Polished Diorite Redstone Torch", 
    "block.more_beautiful_torches.polished_diorite_soul_torch": "Polished Diorite Soul Torch", 
    "block.more_beautiful_torches.polished_diorite_torch": "Polished Diorite Torch", 
    "block.more_beautiful_torches.polished_granite_redstone_torch": "Polished Granite Redstone Torch", 
    "block.more_beautiful_torches.polished_granite_soul_torch": "Polished Granite Soul Torch", 
    "block.more_beautiful_torches.polished_granite_torch": "Polished Granite Torch", 
    "block.more_beautiful_torches.prismarine_bricks_redstone_torch": "Prismarine Bricks Redstone Torch", 
    "block.more_beautiful_torches.prismarine_bricks_soul_torch": "Prismarine Bricks Soul Torch", 
    "block.more_beautiful_torches.prismarine_bricks_torch": "Prismarine Bricks Torch", 
    "block.more_beautiful_torches.pumpkin_redstone_torch": "Pumpkin Redstone Torch", 
    "block.more_beautiful_torches.pumpkin_soul_torch": "Pumpkin Soul Torch", 
    "block.more_beautiful_torches.pumpkin_torch": "Pumpkin Torch", 
    "block.more_beautiful_torches.purple_terracotta_redstone_torch": "Purple Terracotta Redstone Torch", 
    "block.more_beautiful_torches.purple_terracotta_soul_torch": "Purple Terracotta Soul Torch", 
    "block.more_beautiful_torches.purple_terracotta_torch": "Purple Terracotta Torch", 
    "block.more_beautiful_torches.purple_wool_redstone_torch": "Purple Wool Redstone Torch", 
    "block.more_beautiful_torches.purple_wool_soul_torch": "Purple Wool Soul Torch", 
    "block.more_beautiful_torches.purple_wool_torch": "Purple Wool Torch", 
    "block.more_beautiful_torches.purpur_block_redstone_torch": "Purpur Block Redstone Torch", 
    "block.more_beautiful_torches.purpur_block_soul_torch": "Purpur Block Soul Torch", 
    "block.more_beautiful_torches.purpur_block_torch": "Purpur Block Torch", 
    "block.more_beautiful_torches.purpur_pillar_redstone_torch": "Purpur Pillar Redstone Torch", 
    "block.more_beautiful_torches.purpur_pillar_soul_torch": "Purpur Pillar Soul Torch", 
    "block.more_beautiful_torches.purpur_pillar_torch": "Purpur Pillar Torch", 
    "block.more_beautiful_torches.quartz_block_redstone_torch": "Quartz Block Redstone Torch", 
    "block.more_beautiful_torches.quartz_block_soul_torch": "Quartz Block Soul Torch", 
    "block.more_beautiful_torches.quartz_block_torch": "Quartz Block Torch", 
    "block.more_beautiful_torches.quartz_bricks_redstone_torch": "Quartz Bricks Redstone Torch", 
    "block.more_beautiful_torches.quartz_bricks_soul_torch": "Quartz Bricks Soul Torch", 
    "block.more_beautiful_torches.quartz_bricks_torch": "Quartz Bricks Torch", 
    "block.more_beautiful_torches.quartz_pillar_redstone_torch": "Quartz Pillar Redstone Torch", 
    "block.more_beautiful_torches.quartz_pillar_soul_torch": "Quartz Pillar Soul Torch", 
    "block.more_beautiful_torches.quartz_pillar_torch": "Quartz Pillar Torch", 
    "block.more_beautiful_torches.raw_copper_block_redstone_torch": "Raw Copper Block Redstone Torch", 
    "block.more_beautiful_torches.raw_copper_block_soul_torch": "Raw Copper Block Soul Torch", 
    "block.more_beautiful_torches.raw_copper_block_torch": "Raw Copper Block Torch", 
    "block.more_beautiful_torches.raw_gold_block_redstone_torch": "Raw Gold Block Redstone Torch", 
    "block.more_beautiful_torches.raw_gold_block_soul_torch": "Raw Gold Block Soul Torch", 
    "block.more_beautiful_torches.raw_gold_block_torch": "Raw Gold Block Torch", 
    "block.more_beautiful_torches.raw_iron_block_redstone_torch": "Raw Iron Block Redstone Torch", 
    "block.more_beautiful_torches.raw_iron_block_soul_torch": "Raw Iron Block Soul Torch", 
    "block.more_beautiful_torches.raw_iron_block_torch": "Raw Iron Block Torch", 
    "block.more_beautiful_torches.redstone_block_redstone_torch": "Redstone Block Redstone Torch", 
    "block.more_beautiful_torches.redstone_block_soul_torch": "Redstone Block Soul Torch", 
    "block.more_beautiful_torches.redstone_block_torch": "Redstone Block Torch", 
    "block.more_beautiful_torches.redstone_ore_redstone_torch": "Redstone Ore Redstone Torch", 
    "block.more_beautiful_torches.redstone_ore_soul_torch": "Redstone Ore Soul Torch", 
    "block.more_beautiful_torches.redstone_ore_torch": "Redstone Ore Torch", 
    "block.more_beautiful_torches.red_mushroom_redstone_torch": "Red Mushroom Redstone Torch", 
    "block.more_beautiful_torches.red_mushroom_soul_torch": "Red Mushroom Soul Torch", 
    "block.more_beautiful_torches.red_mushroom_torch": "Red Mushroom Torch", 
    "block.more_beautiful_torches.red_mushroom_block_redstone_torch": "Red Mushroom Block Redstone Torch", 
    "block.more_beautiful_torches.red_mushroom_block_soul_torch": "Red Mushroom Block Soul Torch", 
    "block.more_beautiful_torches.red_mushroom_block_torch": "Red Mushroom Block Torch", 
    "block.more_beautiful_torches.red_nether_bricks_redstone_torch": "Red Nether Bricks Redstone Torch", 
    "block.more_beautiful_torches.red_nether_bricks_soul_torch": "Red Nether Bricks Soul Torch", 
    "block.more_beautiful_torches.red_nether_bricks_torch": "Red Nether Bricks Torch", 
    "block.more_beautiful_torches.red_sand_redstone_torch": "Red Sand Redstone Torch", 
    "block.more_beautiful_torches.red_sand_soul_torch": "Red Sand Soul Torch", 
    "block.more_beautiful_torches.red_sand_torch": "Red Sand Torch", 
    "block.more_beautiful_torches.red_sandstone_redstone_torch": "Red Sandstone Redstone Torch", 
    "block.more_beautiful_torches.red_sandstone_soul_torch": "Red Sandstone Soul Torch", 
    "block.more_beautiful_torches.red_sandstone_torch": "Red Sandstone Torch", 
    "block.more_beautiful_torches.red_terracotta_redstone_torch": "Red Terracotta Redstone Torch", 
    "block.more_beautiful_torches.red_terracotta_soul_torch": "Red Terracotta Soul Torch", 
    "block.more_beautiful_torches.red_terracotta_torch": "Red Terracotta Torch", 
    "block.more_beautiful_torches.red_wool_redstone_torch": "Red Wool Redstone Torch", 
    "block.more_beautiful_torches.red_wool_soul_torch": "Red Wool Soul Torch", 
    "block.more_beautiful_torches.red_wool_torch": "Red Wool Torch", 
    "block.more_beautiful_torches.reinforced_deepslate_redstone_torch": "Reinforced Deepslate Redstone Torch", 
    "block.more_beautiful_torches.reinforced_deepslate_soul_torch": "Reinforced Deepslate Soul Torch", 
    "block.more_beautiful_torches.reinforced_deepslate_torch": "Reinforced Deepslate Torch", 
    "block.more_beautiful_torches.respawn_anchor_redstone_torch": "Respawn Anchor Redstone Torch", 
    "block.more_beautiful_torches.respawn_anchor_soul_torch": "Respawn Anchor Soul Torch", 
    "block.more_beautiful_torches.respawn_anchor_torch": "Respawn Anchor Torch", 
    "block.more_beautiful_torches.rooted_dirt_redstone_torch": "Rooted Dirt Redstone Torch", 
    "block.more_beautiful_torches.rooted_dirt_soul_torch": "Rooted Dirt Soul Torch", 
    "block.more_beautiful_torches.rooted_dirt_torch": "Rooted Dirt Torch", 
    "block.more_beautiful_torches.sand_redstone_torch": "Sand Redstone Torch", 
    "block.more_beautiful_torches.sand_soul_torch": "Sand Soul Torch", 
    "block.more_beautiful_torches.sand_torch": "Sand Torch", 
    "block.more_beautiful_torches.sandstone_redstone_torch": "Sandstone Redstone Torch", 
    "block.more_beautiful_torches.sandstone_soul_torch": "Sandstone Soul Torch", 
    "block.more_beautiful_torches.sandstone_torch": "Sandstone Torch", 
    "block.more_beautiful_torches.sculk_redstone_torch": "Sculk Redstone Torch", 
    "block.more_beautiful_torches.sculk_soul_torch": "Sculk Soul Torch", 
    "block.more_beautiful_torches.sculk_torch": "Sculk Torch", 
    "block.more_beautiful_torches.sculk_catalyst_redstone_torch": "Sculk Catalyst Redstone Torch", 
    "block.more_beautiful_torches.sculk_catalyst_soul_torch": "Sculk Catalyst Soul Torch", 
    "block.more_beautiful_torches.sculk_catalyst_torch": "Sculk Catalyst Torch", 
    "block.more_beautiful_torches.shroomlight_redstone_torch": "Shroomlight Redstone Torch", 
    "block.more_beautiful_torches.shroomlight_soul_torch": "Shroomlight Soul Torch", 
    "block.more_beautiful_torches.shroomlight_torch": "Shroomlight Torch", 
    "block.more_beautiful_torches.slime_block_redstone_torch": "Slime Block Redstone Torch", 
    "block.more_beautiful_torches.slime_block_soul_torch": "Slime Block Soul Torch", 
    "block.more_beautiful_torches.slime_block_torch": "Slime Block Torch", 
    "block.more_beautiful_torches.smooth_basalt_redstone_torch": "Smooth Basalt Redstone Torch", 
    "block.more_beautiful_torches.smooth_basalt_soul_torch": "Smooth Basalt Soul Torch", 
    "block.more_beautiful_torches.smooth_basalt_torch": "Smooth Basalt Torch", 
    "block.more_beautiful_torches.smooth_quartz_redstone_torch": "Smooth Quartz Redstone Torch", 
    "block.more_beautiful_torches.smooth_quartz_soul_torch": "Smooth Quartz Soul Torch", 
    "block.more_beautiful_torches.smooth_quartz_torch": "Smooth Quartz Torch", 
    "block.more_beautiful_torches.smooth_red_sandstone_redstone_torch": "Smooth Red Sandstone Redstone Torch", 
    "block.more_beautiful_torches.smooth_red_sandstone_soul_torch": "Smooth Red Sandstone Soul Torch", 
    "block.more_beautiful_torches.smooth_red_sandstone_torch": "Smooth Red Sandstone Torch", 
    "block.more_beautiful_torches.smooth_sandstone_redstone_torch": "Smooth Sandstone Redstone Torch", 
    "block.more_beautiful_torches.smooth_sandstone_soul_torch": "Smooth Sandstone Soul Torch", 
    "block.more_beautiful_torches.smooth_sandstone_torch": "Smooth Sandstone Torch", 
    "block.more_beautiful_torches.smooth_stone_redstone_torch": "Smooth Stone Redstone Torch", 
    "block.more_beautiful_torches.smooth_stone_soul_torch": "Smooth Stone Soul Torch", 
    "block.more_beautiful_torches.smooth_stone_torch": "Smooth Stone Torch", 
    "block.more_beautiful_torches.snow_block_redstone_torch": "Snow Block Redstone Torch", 
    "block.more_beautiful_torches.snow_block_soul_torch": "Snow Block Soul Torch", 
    "block.more_beautiful_torches.snow_block_torch": "Snow Block Torch", 
    "block.more_beautiful_torches.soul_sand_redstone_torch": "Soul Sand Redstone Torch", 
    "block.more_beautiful_torches.soul_sand_soul_torch": "Soul Sand Soul Torch", 
    "block.more_beautiful_torches.soul_sand_torch": "Soul Sand Torch", 
    "block.more_beautiful_torches.soul_soil_redstone_torch": "Soul Soil Redstone Torch", 
    "block.more_beautiful_torches.soul_soil_soul_torch": "Soul Soil Soul Torch", 
    "block.more_beautiful_torches.soul_soil_torch": "Soul Soil Torch", 
    "block.more_beautiful_torches.sponge_redstone_torch": "Sponge Redstone Torch", 
    "block.more_beautiful_torches.sponge_soul_torch": "Sponge Soul Torch", 
    "block.more_beautiful_torches.sponge_torch": "Sponge Torch", 
    "block.more_beautiful_torches.spruce_log_redstone_torch": "Spruce Log Redstone Torch", 
    "block.more_beautiful_torches.spruce_log_soul_torch": "Spruce Log Soul Torch", 
    "block.more_beautiful_torches.spruce_log_torch": "Spruce Log Torch", 
    "block.more_beautiful_torches.spruce_planks_redstone_torch": "Spruce Planks Redstone Torch", 
    "block.more_beautiful_torches.spruce_planks_soul_torch": "Spruce Planks Soul Torch", 
    "block.more_beautiful_torches.spruce_planks_torch": "Spruce Planks Torch", 
    "block.more_beautiful_torches.stone_redstone_torch": "Stone Redstone Torch", 
    "block.more_beautiful_torches.stone_soul_torch": "Stone Soul Torch", 
    "block.more_beautiful_torches.stone_torch": "Stone Torch", 
    "block.more_beautiful_torches.stone_bricks_redstone_torch": "Stone Bricks Redstone Torch", 
    "block.more_beautiful_torches.stone_bricks_soul_torch": "Stone Bricks Soul Torch", 
    "block.more_beautiful_torches.stone_bricks_torch": "Stone Bricks Torch", 
    "block.more_beautiful_torches.stripped_acacia_log_redstone_torch": "Stripped Acacia Log Redstone Torch", 
    "block.more_beautiful_torches.stripped_acacia_log_soul_torch": "Stripped Acacia Log Soul Torch", 
    "block.more_beautiful_torches.stripped_acacia_log_torch": "Stripped Acacia Log Torch", 
    "block.more_beautiful_torches.stripped_birch_log_redstone_torch": "Stripped Birch Log Redstone Torch", 
    "block.more_beautiful_torches.stripped_birch_log_soul_torch": "Stripped Birch Log Soul Torch", 
    "block.more_beautiful_torches.stripped_birch_log_torch": "Stripped Birch Log Torch", 
    "block.more_beautiful_torches.stripped_crimson_hyphae_redstone_torch": "Stripped Crimson Hyphae Redstone Torch", 
    "block.more_beautiful_torches.stripped_crimson_hyphae_soul_torch": "Stripped Crimson Hyphae Soul Torch", 
    "block.more_beautiful_torches.stripped_crimson_hyphae_torch": "Stripped Crimson Hyphae Torch", 
    "block.more_beautiful_torches.stripped_dark_oak_log_redstone_torch": "Stripped Dark Oak Log Redstone Torch", 
    "block.more_beautiful_torches.stripped_dark_oak_log_soul_torch": "Stripped Dark Oak Log Soul Torch", 
    "block.more_beautiful_torches.stripped_dark_oak_log_torch": "Stripped Dark Oak Log Torch", 
    "block.more_beautiful_torches.stripped_jungle_log_redstone_torch": "Stripped Jungle Log Redstone Torch", 
    "block.more_beautiful_torches.stripped_jungle_log_soul_torch": "Stripped Jungle Log Soul Torch", 
    "block.more_beautiful_torches.stripped_jungle_log_torch": "Stripped Jungle Log Torch", 
    "block.more_beautiful_torches.stripped_mangrove_log_redstone_torch": "Stripped Mangrove Log Redstone Torch", 
    "block.more_beautiful_torches.stripped_mangrove_log_soul_torch": "Stripped Mangrove Log Soul Torch", 
    "block.more_beautiful_torches.stripped_mangrove_log_torch": "Stripped Mangrove Log Torch", 
    "block.more_beautiful_torches.stripped_oak_log_redstone_torch": "Stripped Oak Log Redstone Torch", 
    "block.more_beautiful_torches.stripped_oak_log_soul_torch": "Stripped Oak Log Soul Torch", 
    "block.more_beautiful_torches.stripped_oak_log_torch": "Stripped Oak Log Torch", 
    "block.more_beautiful_torches.stripped_spruce_log_redstone_torch": "Stripped Spruce Log Redstone Torch", 
    "block.more_beautiful_torches.stripped_spruce_log_soul_torch": "Stripped Spruce Log Soul Torch", 
    "block.more_beautiful_torches.stripped_spruce_log_torch": "Stripped Spruce Log Torch", 
    "block.more_beautiful_torches.stripped_warped_hyphae_redstone_torch": "Stripped Warped Hyphae Redstone Torch", 
    "block.more_beautiful_torches.stripped_warped_hyphae_soul_torch": "Stripped Warped Hyphae Soul Torch", 
    "block.more_beautiful_torches.stripped_warped_hyphae_torch": "Stripped Warped Hyphae Torch", 
    "block.more_beautiful_torches.target_redstone_torch": "Target Redstone Torch", 
    "block.more_beautiful_torches.target_soul_torch": "Target Soul Torch", 
    "block.more_beautiful_torches.target_torch": "Target Torch", 
    "block.more_beautiful_torches.terracotta_redstone_torch": "Terracotta Redstone Torch", 
    "block.more_beautiful_torches.terracotta_soul_torch": "Terracotta Soul Torch", 
    "block.more_beautiful_torches.terracotta_torch": "Terracotta Torch", 
    "block.more_beautiful_torches.tnt_redstone_torch": "Tnt Redstone Torch", 
    "block.more_beautiful_torches.tnt_soul_torch": "Tnt Soul Torch", 
    "block.more_beautiful_torches.tnt_torch": "Tnt Torch", 
    "block.more_beautiful_torches.tube_coral_block_redstone_torch": "Tube Coral Block Redstone Torch", 
    "block.more_beautiful_torches.tube_coral_block_soul_torch": "Tube Coral Block Soul Torch", 
    "block.more_beautiful_torches.tube_coral_block_torch": "Tube Coral Block Torch", 
    "block.more_beautiful_torches.tuff_redstone_torch": "Tuff Redstone Torch", 
    "block.more_beautiful_torches.tuff_soul_torch": "Tuff Soul Torch", 
    "block.more_beautiful_torches.tuff_torch": "Tuff Torch", 
    "block.more_beautiful_torches.verdant_froglight_redstone_torch": "Verdant Froglight Redstone Torch", 
    "block.more_beautiful_torches.verdant_froglight_soul_torch": "Verdant Froglight Soul Torch", 
    "block.more_beautiful_torches.verdant_froglight_torch": "Verdant Froglight Torch", 
    "block.more_beautiful_torches.warped_fungus_redstone_torch": "Warped Fungus Redstone Torch", 
    "block.more_beautiful_torches.warped_fungus_soul_torch": "Warped Fungus Soul Torch", 
    "block.more_beautiful_torches.warped_fungus_torch": "Warped Fungus Torch", 
    "block.more_beautiful_torches.warped_hyphae_redstone_torch": "Warped Hyphae Redstone Torch", 
    "block.more_beautiful_torches.warped_hyphae_soul_torch": "Warped Hyphae Soul Torch", 
    "block.more_beautiful_torches.warped_hyphae_torch": "Warped Hyphae Torch", 
    "block.more_beautiful_torches.warped_nylium_redstone_torch": "Warped Nylium Redstone Torch", 
    "block.more_beautiful_torches.warped_nylium_soul_torch": "Warped Nylium Soul Torch", 
    "block.more_beautiful_torches.warped_nylium_torch": "Warped Nylium Torch", 
    "block.more_beautiful_torches.warped_planks_redstone_torch": "Warped Planks Redstone Torch", 
    "block.more_beautiful_torches.warped_planks_soul_torch": "Warped Planks Soul Torch", 
    "block.more_beautiful_torches.warped_planks_torch": "Warped Planks Torch", 
    "block.more_beautiful_torches.warped_roots_redstone_torch": "Warped Roots Redstone Torch", 
    "block.more_beautiful_torches.warped_roots_soul_torch": "Warped Roots Soul Torch", 
    "block.more_beautiful_torches.warped_roots_torch": "Warped Roots Torch", 
    "block.more_beautiful_torches.warped_wart_block_redstone_torch": "Warped Wart Block Redstone Torch", 
    "block.more_beautiful_torches.warped_wart_block_soul_torch": "Warped Wart Block Soul Torch", 
    "block.more_beautiful_torches.warped_wart_block_torch": "Warped Wart Block Torch", 
    "block.more_beautiful_torches.weathered_copper_redstone_torch": "Weathered Copper Redstone Torch", 
    "block.more_beautiful_torches.weathered_copper_soul_torch": "Weathered Copper Soul Torch", 
    "block.more_beautiful_torches.weathered_copper_torch": "Weathered Copper Torch", 
    "block.more_beautiful_torches.weathered_cut_copper_redstone_torch": "Weathered Cut Copper Redstone Torch", 
    "block.more_beautiful_torches.weathered_cut_copper_soul_torch": "Weathered Cut Copper Soul Torch", 
    "block.more_beautiful_torches.weathered_cut_copper_torch": "Weathered Cut Copper Torch", 
    "block.more_beautiful_torches.wet_sponge_redstone_torch": "Wet Sponge Redstone Torch", 
    "block.more_beautiful_torches.wet_sponge_soul_torch": "Wet Sponge Soul Torch", 
    "block.more_beautiful_torches.wet_sponge_torch": "Wet Sponge Torch", 
    "block.more_beautiful_torches.white_terracotta_redstone_torch": "White Terracotta Redstone Torch", 
    "block.more_beautiful_torches.white_terracotta_soul_torch": "White Terracotta Soul Torch", 
    "block.more_beautiful_torches.white_terracotta_torch": "White Terracotta Torch", 
    "block.more_beautiful_torches.white_wool_redstone_torch": "White Wool Redstone Torch", 
    "block.more_beautiful_torches.white_wool_soul_torch": "White Wool Soul Torch", 
    "block.more_beautiful_torches.white_wool_torch": "White Wool Torch", 
    "block.more_beautiful_torches.yellow_terracotta_redstone_torch": "Yellow Terracotta Redstone Torch", 
    "block.more_beautiful_torches.yellow_terracotta_soul_torch": "Yellow Terracotta Soul Torch", 
    "block.more_beautiful_torches.yellow_terracotta_torch": "Yellow Terracotta Torch", 
    "block.more_beautiful_torches.yellow_wool_redstone_torch": "Yellow Wool Redstone Torch", 
    "block.more_beautiful_torches.yellow_wool_soul_torch": "Yellow Wool Soul Torch", 
    "block.more_beautiful_torches.yellow_wool_torch": "Yellow Wool Torch"
}
